### ISSUE TITLE
HTML tag autocompletion isn't case sensitive

### ISSUE THREAD

**Issue by jasonatmicrosoft** [Microsoft/vscode-html-languageservice#4]
When using VS Code's auto complete in a .html file, it will offer to close a tag like the following example:

`
<myTag>
...
</mytag>
`

This can cause run time errors when using frameworks like Angular 2.

**Comment by aeschli** [comment]
This was fixed by https://github.com/Microsoft/vscode-html-languageservice/commit/e477a37194532bee648eaeff8cda9fa186fc91bd and looks fine to me in VSCode 1.8
![image](https://cloud.githubusercontent.com/assets/6461412/21221160/9fe2fdea-c2bc-11e6-80b5-980b0237d794.png)

Please reopen with details how to reproduce if you still see this in the latest.

**Comment by jasonatmicrosoft** [comment]
Yep! This has definitely been fixed! Thanks for the quick turnaround on this.
